spring.application.name=coding-challenge

# Server configuration
server.port=8080

# Concurrency limit configuration
# Maximum number of concurrent requests
app.concurrency.limit=10
# Timeout for each request in milliseconds
app.concurrency.timeout=100